services:
  - mysql

env:
  - DB_HOST="127.0.0.1" DB_PORT=3306 DB_USER="root" DB_PASS="" DB_NAME="session_test"

language: node_js
node_js:
  - "14"
  - "12"
  - "10"

before_install:
  - "mysql -e 'drop database if exists session_test; create database session_test;'"

install: npm install
script: npm test
